# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Images/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_area = QtWidgets.QFrame(self.content)
        self.login_area.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area.setStyleSheet("border-radius: 10px;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.lineEdit_user = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_user.setGeometry(QtCore.QRect(80, 120, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148, 0, 211);    \n"
"    color: rgb(148, 0, 211);\n"
"}")
        self.lineEdit_user.setMaxLength(10)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_password.setGeometry(QtCore.QRect(80, 200, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148, 0, 211);        \n"
"    color: rgb(148, 0, 211);\n"
"}")
        self.lineEdit_password.setMaxLength(10)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label = QtWidgets.QLabel(self.login_area)
        self.label.setGeometry(QtCore.QRect(60, -10, 331, 51))
        self.label.setStyleSheet("color: rgb(95, 95, 95);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.login_area)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 331, 51))
        self.label_2.setStyleSheet("color: rgb(95, 95, 95);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_password_2 = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_password_2.setGeometry(QtCore.QRect(80, 280, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEdit_password_2.setFont(font)
        self.lineEdit_password_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148, 0, 211);        \n"
"    color: rgb(148, 0, 211);\n"
"}")
        self.lineEdit_password_2.setMaxLength(16)
        self.lineEdit_password_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.lineEdit_password_3 = QtWidgets.QComboBox(self.login_area)#Mudei aqui
        self.lineEdit_password_3.setGeometry(QtCore.QRect(80, 350, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)

        self.lineEdit_password_3.setStyleSheet("font: 75 10pt \"Segoe UI\";\n"
"    border: 2px solid rgb(55, 55,55);\n"
"    border-radius: 2px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"\n"
"")#Aqui tbm
  

        self.lineEdit_password_3.setObjectName("lineEdit_password_3")
        self.lineEdit_password_3.addItem("")
        self.lineEdit_password_3.addItem("")
        self.pushButton_login_2 = QtWidgets.QPushButton(self.login_area)
        self.pushButton_login_2.setGeometry(QtCore.QRect(40, 450, 161, 50))
        self.pushButton_login_2.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(148, 0, 211);\n"
"    border: 2px solid rgb(128, 0, 128);    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}")
        self.pushButton_login_2.setObjectName("pushButton_login_2")
        self.pushButton_login_3 = QtWidgets.QPushButton(self.login_area)
        self.pushButton_login_3.setGeometry(QtCore.QRect(220, 450, 161, 50))
        self.pushButton_login_3.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(148, 0, 211);\n"
"    border: 2px solid rgb(128, 0, 128);    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}")
        self.pushButton_login_3.setObjectName("pushButton_login_3")
        self.horizontalLayout.addWidget(self.login_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(15, 15, 15)")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_credits = QtWidgets.QLabel(self.bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(75, 75, 75);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_2.addWidget(self.label_credits)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.lineEdit_user.setPlaceholderText(_translate("MainWindow", "Inserir Usuário"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Inseri Senha"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#959595;\">TELA DE CADASTRO</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; font-weight:600; color:#959595;\">Cadastrar Usuário </span></p></body></html>"))
        self.lineEdit_password_2.setPlaceholderText(_translate("MainWindow", "Inserir Cargo"))
        self.pushButton_login_2.setText(_translate("MainWindow", "Cadastrar Usuário"))
        self.pushButton_login_3.setText(_translate("MainWindow", "Cancelar"))
        self.label_credits.setText(_translate("MainWindow", "Created by: JSolutions - CD RJ - 2021"))
        self.lineEdit_password_3.setItemText(0,_translate("MainWindow", "Administrador"))
        self.lineEdit_password_3.setItemText(1,_translate("MainWindow", "Usuário"))
import template.files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_cadastrar()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
